import { NextPage } from "next"
import Head from "next/head"
import ContactForm from "../../components/contact-form"
import Footer from "../../components/footer"
import Header from "../../components/header"
import { NewSpapper } from "../../imgs/image"

const GetFreeQuote: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Get free quote - DLiTi Landscape</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='anonymous' />
            </Head>
            <Header />
            <div className="p-1 shadow"></div>
            <main className="container mx-auto px-4 py-6">
                <div className="font-bold mb-6" style={{ fontSize: 35 }}>Get free quote</div>
                <div className="md:flex gap-6">
                    <div className="md:w-1/2 mb-4">
                        <ContactForm />
                    </div>
                    <div className="md:w-1/2">
                        <div className="mb-4">
                            DLiTi is your trusted Hobart supplier for fencing that has as attractive as it is secure, not to mention gates, decking, pergolas, balustrades, handrails, security cages and pool safety features. We’re excited to share our full range of products with you, so by all means drop by our showroom in Glenorchy for a browse and chat. Our staffs are always ready to help, and we know we can provide the latest products and services to meet your requirements.
                        </div>
                        <div className="flex justify-center mb-4">
                        <NewSpapper />
                        </div>
                        <div className="mb-4">
                        We are happy to provide you with an estimate based on the information you provide. However, to ensure we are selecting the best product for you and giving you an accurate price, an onsite courtesy visit by one of our qualified tradesmen is always included in our service. We look forward to both meeting and working with you!
                        </div>
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    )
}

export default GetFreeQuote