import { NextPage } from "next"
import Head from "next/head"
import Footer from "../../components/footer"
import Header from "../../components/header"

const Service: NextPage = () => {
    const data = [
        {
            id: 1,
            name: 'Treated pine'
        },
        {
            id: 2,
            name: 'Merbau'
        },
        {
            id: 3,
            name: 'Composite'
        }
    ]
    return (
        <div>
            <Head>
                <title>Service - DLiTi Landscape</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='anonymous' />
            </Head>
            <Header />
            <main className="container mx-auto px-4 py-10">
                <div className="font-bold mb-6" style={{ fontSize: 35 }}>Service</div>
                <div className="md:grid grid-cols-4 gap-10">
                    {
                        data.map(x => (
                            <div className="h-32 rounded-xl text-2xl font-bold flex items-center justify-center bg-slate-800 hover:bg-slate-900 text-white" key={x.id}>
                                {x.name}
                            </div>
                        ))
                    }
                </div>
            </main>
            <Footer />
        </div>
    )
}

export default Service