import type { NextPage } from 'next'
import Head from 'next/head'
import AboutUs from '../components/about-us'
import FeatureBox from '../components/feature-box'
import Footer from '../components/footer'
import Header from '../components/header'
import WhyChooseUs from '../components/why-choose-us'
import { Fossil, Nuclear, Renewables } from '../imgs/icon'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>DLiTi Landscape</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='anonymous' />
      </Head>

      <Header/>

      <main>
        <div className='first-box'>
        </div>
        <div className='container mx-auto pb-20 px-4'>
          <div className='py-20'>
            <div className='text-red-500'>We are DLiTi Landscape</div>
            <div style={{ fontSize: 72, letterSpacing: '-0.09em' }} className="font-semibold mb-2">
              <div>We energize the lives of</div>
              <div className='text-red-500'>170 million people every day</div>
            </div>
            <div className='text-gray-600 mb-6' style={{ maxWidth: 584 }}>
              We are working actively to reduce climate emissions, put a price on carbon, and benefits societis around the world.
            </div>
            <div className='py-4'>
              <a className='px-10 py-4 bg-gray-100 rounded text-red-500' href='https://www.facebook.com/DLiTiKingston'>Get to know us</a>
            </div>
          </div>
        </div>
        <div className='container mx-auto mb-20'>
          <div>
            <div className='md:grid grid-cols-3'>
              <FeatureBox icon={<Fossil />} index={0} name='Fossil resources' description='Leverage agile frameworks to provide a robust synopsis for high level overviews' />
              <FeatureBox icon={<Nuclear />} index={1} name='NUCLEAR ENERGY' description='Leverage agile frameworks to provide a robust synopsis for high level overviews' />
              <FeatureBox icon={<Renewables />} index={2} name='RENEWABLES AND CCS' description='Leverage agile frameworks to provide a robust synopsis for high level overviews' />
            </div>
          </div>
          <AboutUs />
        </div>
        <WhyChooseUs />
      </main>
      <Footer />
    </div>
  )
}

export default Home
